const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = {};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../atlas/radiology/linked_math.js'),'utf8'),context);
const m=context.AtlasLinkedMath;
const matrix=[[1,0,0,0],[0,1,0,0],[0,0,1,0]];
const close=(actual,expected)=>actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-9));
close(m.project([2,4,2],matrix),[1,2,2]);
assert.equal(m.project([2,4,-2],matrix),null);
assert.equal(m.barycentric([5,5],[0,0],[1,0],[0,1]),null);
assert.equal(m.barycentric([0,0],[0,0],[1,1],[2,2]),null);
const vertices=[[0,0,1],[2,0,2],[0,2,2],[0,0,2],[4,0,4],[0,4,4]];
const faces=[[3,4,5],[0,1,2]];
const hit=m.pickImage([.25,.25],vertices,faces,matrix);
close(hit.point,[1/3,1/3,4/3]);
close(m.project(hit.point,matrix),[.25,.25,4/3]);
assert.equal(m.pickImage([5,5],vertices,faces,matrix),null);
console.log('Linked math: analytic projection, perspective interpolation, nearest surface and misses passed.');
